#!/bin/bash

# Test...
# curl --data "title=my%20new%20note&body=BLAHHHH"  http://127.0.0.1/cgi-bin/bash_crud/notes/create

source functions


##############
# Controller #
##############

# Read the post data from stdin
POST_PARAMS=`cat "${1:-/dev/stdin}" > "${2:-/dev/stdout}"`

ID=`calculate_next_id`
# echo "The next id is:  ${ID}"

# POST_PARAMS="title=none&body=none;"
# Do regex to collect /title=()[&$]/

# extract_title_from_query_string
TITLE=""
TITLE=`echo ${POST_PARAMS} | grep -P 'title=([^&]*)&' -o | tr \& ' '`
TITLE=`sed 's/;//g' <<< ${TITLE}`
TITLE=`sed 's/title=//g' <<< ${TITLE}`

# extract_body_from_query_string
BODY=""
BODY=`echo ${POST_PARAMS} | grep -P 'body=([^&]*)&' -o | tr \& ' '`
BODY=`sed 's/;//g' <<< ${BODY}`
BODY=`sed 's/body=//g' <<< ${BODY}`

# save_note_to_database
echo "${ID}; ${TITLE}; ${BODY}" >> flat_file.db

echo "title=asdf+asdf&body=asdf+asdf+asdf&commit=Submit" | grep -P 'title=(.*)&' -o

# NOTE_ID=1
# RECORD=`eval ${QUERY_CMD}`


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head><style>label {font-weight:bold;}</style><body>"

echo "<div>Note Created!</div>"
echo "<a href='/cgi-bin/bash_crud/notes'>back to index</a>"

# DEBUG PRINTOUT
# echo ${POST_PARAMS}
# echo "<br>"
# echo ${ID}
# echo "<br>"
# echo ${TITLE}
# echo "<br>"
# echo ${BODY}
# echo "<br>"

echo "</body></html>"
