#!/bin/bash

# Test...
# curl --data "title=my%20new%20note&body=BLAHHHH"  http://127.0.0.1/cgi-bin/bash_crud/notes/create

source functions


##############
# Controller #
##############

# Read the post data from stdin
POST_PARAMS=`cat "${1:-/dev/stdin}" > "${2:-/dev/stdout}"`

ID=`calculate_next_id`
# echo "The next id is:  ${ID}"

# POST_PARAMS="title=none&body=none;"
# Do regex to collect /title=()[&$]/



attributes=(`extract_title_from_post_data ${POST_PARAMS}`)
TITLE=${attributes[0]}
BODY=${attributes[1]}

# save_note_to_database
echo "${ID}; ${TITLE}; ${BODY}" >> flat_file.db


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head><style>label {font-weight:bold;}</style><body>"

echo "<div>Note Created!</div>"
echo "<a href='/cgi-bin/bash_crud/notes'>back to index</a>"

# DEBUG PRINTOUT
# echo ${POST_PARAMS}
# echo "<br>"
# echo ${ID}
# echo "<br>"
# echo ${TITLE}
# echo "<br>"
# echo ${BODY}
# echo "<br>"

echo "</body></html>"
