#!/bin/bash

source functions

##############
# Controller #
##############

# REQUEST_URI="/cgi-bin/bash_crud/notes/1"
# get_id_from_request_uri
get_id_from_request_uri ()
{
  echo ${REQUEST_URI} | egrep -o '[0-9]+$'
}

NOTE_ID=`get_id_from_request_uri ${REQUEST_URI}`

# 1) Get the record to delete
QUERY_CMD="sed -n '/^${NOTE_ID};/p' flat_file.db"
RECORD=`eval ${QUERY_CMD}`

# 2) Delete the record
# DB_AFTER_DELETION=`sed '/1; important note; I have an important note/d' flat_file.db`
DEL_RECORD_CMD="sed '/${RECORD}/d' flat_file.db"
DB_AFTER_DELETION=`eval ${DEL_RECORD_CMD}`
`echo -e "${DB_AFTER_DELETION}" > flat_file.db`


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head>
        <script src='/jquery-3.0.0.min.js'></script>
        <script src='/bash_crud.js'></script>
        <style>label {font-weight:bold;}</style><body>"
echo "<h1>Bash CRUD!</h1><p>Welcome to bash crud!</p>"

echo "You deleted note with id == ${NOTE_ID}!"
echo "${DB_AFTER_DELETION}"

echo "</body></html>"
