#!/bin/bash

source functions

##############
# Controller #
##############

RECORD=`query_record_by_id ${ID}`
parse_record_to_collect_values


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head>
        <meta http-equiv='content-type' content='text/html; charset=utf-8' />
        <script src='/jquery-3.0.0.min.js'></script>
        <script src='/bash_crud.js'></script>
        <style>label {font-weight:bold;}</style><body>"

echo "<h1>Edit</h1><p>Edit this existing note!</p>"

echo "<form action='/cgi-bin/bash_crud/notes/${ID}' method='put'
        accept-charset='UTF-8'>
        <input id='title' name='title' type='text' value='${TITLE}'></input>
        <input id='body' name='body' type='text' value='${BODY}'></input>
        <input type='submit' name='commit' value='Submit' />
      </form>"

echo "</body></html>"
