#!/bin/bash

##############
# Controller #
##############

QUERY_CMD="sed -n '/^${NOTE_ID};/p' flat_file.db"


# reads NOTE_ID
show_html_for_note_by_id ()
{
  # grep through the file
  RECORD=`eval ${QUERY_CMD}`

  parse_record_to_collect_values # sets TITLE and BODY
  markup="<div><label>title:</label><div>${TITLE}</div> <label>body:</label><div>${BODY}</div></div><br>"

  BODY_MARKUP[0]=${markup}
}

parse_record_to_collect_values ()
{
  IFS=';'
  # iterate over each line of flat_file.db and send it's input into an element of NOTE_LINES
  while read -ra p; do
    TITLE=${p[1]}
    BODY=${p[2]}
  done <<<"${RECORD}"
}



# index
convert_notes_into_markup ()
{
  COUNT=$((0))
  IFS=';'
  # iterate over each line of flat_file.db and send it's input into an element of NOTE_LINES
  while read -ra p; do
    # NOTE_MARKUP[$((COUNT))]=${p[@]}
    title=${p[1]}
    body=${p[2]}
    markup="<div><label>title:</label><div>${title}</div> <label>body:</label><div>${body}</div></div><br>"
    NOTE_MARKUP[$((COUNT))]=${markup}
    COUNT=$((COUNT+1))
  done <flat_file.db
}
