#!/bin/bash

##############
# Controller #
##############


convert_notes_into_markup ()
{
  COUNT=$((0))
  IFS=';'
  # iterate over each line of flat_file.db and send it's input into an element of NOTE_LINES
  while read -ra p; do
    # NOTE_MARKUP[$((COUNT))]=${p[@]}
    title=${p[1]}
    body=${p[2]}
    markup="<div><label>title:</label><div>${title}</div> <label>body:</label><div>${body}</div></div><br>"
    NOTE_MARKUP[$((COUNT))]=${markup}
    COUNT=$((COUNT+1))
  done <flat_file.db
}

convert_notes_into_markup


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head><style>label {font-weight:bold;}</style><body>"
echo "<h1>Bash CRUD!</h1><p>Welcome to bash crud!</p>"

echo ${NOTE_MARKUP[@]}

echo "</body></html>"
