#!/bin/bash

source functions

##############
# Controller #
##############

convert_notes_into_markup


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head><style>label {font-weight:bold;}</style><body>"
echo "<h1>Bash CRUD!</h1><p>Welcome to bash crud!</p>"

echo ${NOTE_MARKUP[@]}

echo "</body></html>"
