#!/bin/bash

source functions

##############
# Controller #
##############

# REQUEST_METHOD=GET
NOTE_ID="1"
NOTE_ID="${ID}"

# Populates BODY_MARKUP
BODY_MARKUP=`show_html_for_note_by_id ${NOTE_ID}`


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head><style>label {font-weight:bold;}</style><body>"
echo "<h1>Bash CRUD!</h1><p>Welcome to bash crud!</p>"

echo ${BODY_MARKUP}

echo "<a href='/cgi-bin/bash_crud/notes'>back to index</a>"

echo "</body></html>"
