#!/bin/bash

source functions

##############
# Controller #
##############

# REQUEST_METHOD=GET
NOTE_ID="1"

# Populates BODY_MARKUP
show_html_for_note_by_id


##########
# header #
##########

echo Content-type: text/html
echo


########
# body #
########

echo "<html><head><style>label {font-weight:bold;}</style><body>"
echo "<h1>Bash CRUD!</h1><p>Welcome to bash crud!</p>"

echo ${BODY_MARKUP[@]}

echo "</body></html>"
